stages:
  - test
  - build_app
  - build_image
variables:
  APP_IMAGE: $REPO_SERVER/$REPO_NAMESPACE/$CI_PROJECT_NAME:$CI_COMMIT_SHORT_SHA

golangci-lint:
  stage: test
  image: golangci/golangci-lint
  script:
    - go env -w GO111MODULE=on
    - go env -w GOPROXY=https://goproxy.cn,direct
    - golangci-lint run -v -E gofmt -E golint

build_app:
  stage: build_app
  image:
    name: cr.d.xiaomi.net/containercloud/golang:1.15-centos7
    entrypoint: [""]
  variables:
    GO111MODULE: 'on'
    GOPROXY: https://goproxy.cn
  script:
    - echo "build"
    - cd $CI_PROJECT_DIR
    - make
  artifacts:
    paths:
      - main
  after_script:
    - echo "build completed"
  when: always

build_image:
  stage: build_image
  image:
    name: cr.d.xiaomi.net/containercloud/kaniko-executor-xiaomi:release
    entrypoint: [""]
  script:
    - echo $CI_COMMIT_SHORT_SHA
    - echo "build image"
    - echo "{\"auths\":{\"$REPO_SERVER\":{\"username\":\"$REPO_USER\",\"password\":\"$REPO_PASS\"}}}" > /kaniko/.docker/config.json
    - /kaniko/executor --context $CI_PROJECT_DIR --destination $APP_IMAGE --validate-image
  after_script:
    - echo "bulid completed"
  when: on_success
  only:
    - master
